name: ren_finance_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SVG
  flutter_svg: ^2.0.6

  # iOS style icons.
  cupertino_icons: ^1.0.2

  # App internatiolization
  intl: ^0.18.1


  # Code generation for assets
  flutter_gen: ^5.3.1

  # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  # routing
  auto_route: ^7.8.1
  # logger
  l: ^4.0.2
  
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.1
  dio: ^5.3.4
  get_it: ^7.6.4
  image_picker: ^1.0.4
  riverpod: ^2.5.1
  provider: ^6.1.2
  sqflite: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
flutter_gen:
  output: lib/src/gen
  integrations:
    flutter_svg: true
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/database/


  

  
  fonts:
    - family: Righteous
      fonts:
        - asset:  assets/fonts/Righteous-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
